version: '3'

services:
  node:
    container_name: myriad-node-parachain
    image: myriadsocial/myriad-node-parachain
    build:
      context: ../../
      dockerfile: .maintain/docker/Dockerfile
    volumes:
      - data:/data
    command: --dev
    ports:
      - 30333:30333
      - 9933:9933
      - 9944:9944
      - 9615:9615
    networks:
      myriad:
        ipv4_address: 172.27.1.1
        aliases:
          - node

volumes:
  data:

networks:
  myriad:
    external: true
